### PR TITLE
Adding uns_functions module to flattener_mods. Moving over uns functi…

### PR DESCRIPTION
**Pull request by Jchaffer787**
Moving uns functions from flattener to new module uns_functions.py within flattener_mods folder. Also moved over section of main code in flattener into a new function in the uns_functions.py module.

### CODE REVIEW

**Comment by jychien** [comment]
Got the following error when flattening LATDF584NGT:

> Traceback (most recent call last):
  File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 1134, in <module>
    main(args.file)
  File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 1055, in main
    process_spatial(glob)
NameError: name 'process_spatial' is not defined

I added tried `fm.process_spatial(glob)`, and then there were a few other things that popped up.

**Comment by jychien** [comment]
Thanks, Jim! I'm still running through the a few more test datasets, but I did notice that it prints an empty list at the very end. Not sure where this coming from in the code.

Screenshot 2024-05-13 at 10 52 12 AM

**Comment by Jchaffer787** [comment]
Simple fix, forgot to do a check if the warnings lists being returned from the functions were empty before appending them to the overall warning_list.

**Comment by jychien** [comment]
Thanks, Jim! It looks good to me!

**Review by jychien — APPROVED** [review]

**Pull request merged**
