### PR TITLE
add imports of re and mcolors

### PR DESCRIPTION
**Pull request by jychien**
@Jchaffer787 quick add of import of libraries for uns_functions.py. Sample processed matrix file: LATDF622OJJ

### CODE REVIEW

**Comment by Jchaffer787** [comment]
I'm getting the following error when I run LATDF622OJJ:
`  File "/Users/jchaffer/Desktop/Curation/lattice-tools/scripts/flattener.py", line 1153, in <module>
    main(args.file)
  File "/Users/jchaffer/Desktop/Curation/lattice-tools/scripts/flattener.py", line 1062, in main
    glob.mfinal_adata.var_names_make_unique()
  File "/Users/jchaffer/opt/anaconda3/envs/cxg/lib/python3.9/site-packages/anndata/_core/anndata.py", line 1806, in var_names_make_unique
    self.var_names = utils.make_index_unique(self.var.index, join)
  File "/Users/jchaffer/opt/anaconda3/envs/cxg/lib/python3.9/site-packages/anndata/utils.py", line 253, in make_index_unique
    values_dup[i] = tentative_new_name
  File "/Users/jchaffer/opt/anaconda3/envs/cxg/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 261, in __setitem__
    value = self._validate_setitem_value(value)
  File "/Users/jchaffer/opt/anaconda3/envs/cxg/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 1589, in _validate_setitem_value
    return self._validate_scalar(value)
  File "/Users/jchaffer/opt/anaconda3/envs/cxg/lib/python3.9/site-packages/pandas/core/arrays/categorical.py", line 1614, in _validate_scalar
    raise TypeError(
TypeError: Cannot setitem on a Categorical with a new category (NPIPA9-1), set the categories first`

**Comment by jychien** [comment]
@Jchaffer787 Hm.. that's an odd line to be erroring on. Did you try running from python 3.11 environment?

**Comment by Jchaffer787** [comment]
My bad. Have set up a 3.11 environment, now getting this error:
```
  File "/Users/jchaffer/Desktop/Curation/lattice-tools/scripts/flattener.py", line 1153, in <module>
    main(args.file)
  File "/Users/jchaffer/Desktop/Curation/lattice-tools/scripts/flattener.py", line 1123, in main
    warnings = fm.copy_over_uns(glob, reserved_uns)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jchaffer/Desktop/Curation/lattice-tools/scripts/flattener_mods/uns_functions.py", line 121, in copy_over_uns
    if check_not_empty(v):
       ^^^^^^^^^^^^^^^^^^
  File "/Users/jchaffer/Desktop/Curation/lattice-tools/scripts/flattener_mods/uns_functions.py", line 86, in check_not_empty
    and not (isinstance(value, (np.bool_, np.bool)))
                                          ^^^^^^^
  File "/Users/jchaffer/opt/anaconda3/envs/cxg_new/lib/python3.11/site-packages/numpy/__init__.py", line 324, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations. Did you mean: 'bool_'?
```

**Comment by Jchaffer787** [comment]
@jychien Works now! Took a look at the imports and it looks good to me!

**Pull request merged**
