### PR TITLE
removed unused dataset object query

### PR DESCRIPTION
**Pull request by jychien**
Was a quick update. https://lattice.atlassian.net/browse/TOOLS-168. Looks like I had some extra code floating around. Thanks for catching that, @jahilton

### CODE REVIEW

**Comment by jychien** [comment]
Let me know what you guys think @Jchaffer787 @jahilton. Hopefully get_report() is generic enough to be reused. I've held off on moving around any other code as I thought it would be good to not add to much to this ticket.

**Comment by jahilton** [comment]
I think we want to also enable querying a report for objects if you have criteria other than a list of `@id` (so if I want all of the RawSequenceFiles with dataset=<>).
Also, if feeding a list of `@id`s then should be able to parse the type from the `@id`. 
One idea...

A more general function for querying objects...
get_report(obj_type, filters, field_lst, connection)
where filters can be anything `&dataset=<>` or `&@id=<>&@id=<>`

then have a separate function that you send a list of `@id`s to that produces obj_type & filters...
parse_ids(id_lst)
parse out the obj_type, maybe some management if the obj_types vary across `@id`s
then do the join to make the filters
returns obj_type,filters

So in practice...
obj_type, filters = parse_ids(my_list_of_@ids)
my_objs = get_report(obj_type, filters, field_lst, connection):

**Comment by jahilton** [comment]
>should be able to parse the type from the @id.

Not as straightforward I was thinking
But reviewing all pairs - libraries (Library) & antibody (Antibody) are unique. 
Otherwise `obj_type = ''.join([x.capitalize() for x in at_id.split('-')]).rstrip('s')` or `obj_type = at_id.title().replace('-','').rstrip('s')` should work

**Comment by jychien** [comment]
@jahilton @Jchaffer787 Let me know if this works for you guys

**Comment by Jchaffer787** [comment]
Looks good to me!

**Pull request merged**
