### PR TITLE
Tools 182 move gather functions to separate module

### PR DESCRIPTION
**Pull request by Jchaffer787**
Moving gather_rawmatrices, gather_objects, gather_metdata, gather_pooled_metadata, get_value to a separate gather module.

Also improved comment formatting for these functions.

Set up logger so that loggings from gather.py are sent to the same logging function as flattener.

### CODE REVIEW

**Comment by jychien** [comment]
I am getting the following error:

> LATDF190KNY.h5ad was found locally
Traceback (most recent call last):
  File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 1388, in <module>
    main(args.file)
  File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener.py", line 935, in main
    fm.gather_metdata('raw_matrix', cell_metadata['raw_matrix'], values_to_add, [mxr], connection, prop_map)
  File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener_mods/gather.py", line 150, in gather_metdata
    value = get_value(obj,prop)
  File "/Users/jychien/Lattice-Data/lattice-tools/scripts/flattener_mods/gather.py", line 286, in get_value
    return obj.get(prop, unreported_value)
NameError: name 'unreported_value' is not defined

I think it is best to set the global contants file first before merging in these PRs, since you'll need to access these global constants. I think we can first work on TOOLS-170, TOOLS-181, and TOOLS-182 first. We can leave TOOLS-171 (global variables) for until late. After these 3 tickets, let's take a pause to see if there is more of a timeline for schema 5.1 and the visium updates.

**Comment by Jchaffer787** [comment]
Had made the global constants module and set up flatttener/gather to properly import the constants. Have capitalized all constant values according to preferred standards.

**Comment by jychien** [comment]
I ran through the test datasets, and LATDF477OUM came up with an error:

> % cellxgene-schema validate 63d03351-06be-478e-a0db-f7a653b6b19b_489318a0-24c3-4f5c-b105-f084ed0ea026_LATDF477OUM_v5.h5ad
Loading dependencies
Loading validator modules
Starting validation...
WARNING: Validation of raw layer was not performed due to current errors, try again after fixing current errors.
ERROR: 'unknown' in 'uns['default_embedding']' is not valid, it must be a key of 'adata.obsm'.
Validation complete in 0:00:07.187470 with status is_valid=False

**Comment by Jchaffer787** [comment]
Hmm.. are you sure you don't have any local changes? I didn't get that error when I originally ran LATDF477OUM, and I just tried again with a fresh pull and it ran through smoothly as well...

**Comment by jychien** [comment]
Looks like there is no field value for default_embedding for [LATDF477OUM](https://lattice-data.org/processed-matrix-files/LATDF477OUM/?format=json). I had suggested in [this comment](https://lattice.atlassian.net/browse/TOOLS-182?focusedCommentId=18288) to use gather_metdata() to get the dataset metadata. But I didn't realize that the original [report_dataset()](https://github.com/Lattice-Data/lattice-tools/blob/b4c88546a6df013999209a5d9e2337058edd358d/scripts/flattener.py#L519) would ignore fields with values == unreported_value. For most obs fields, the fields with unreported_values are dropped in [drop_cols()](https://github.com/Lattice-Data/lattice-tools/blob/b4c88546a6df013999209a5d9e2337058edd358d/scripts/flattener.py#L1100), but this does not include cleaning up uns fields. Maybe add an extra line in the code around 954 to drop default_embedding if it is unreported. Looks like that is the only field that is optional.

**Comment by jychien** [comment]
Also, was thinking what the value of FLAT_VERSION was. I think initially I had used it for tracking things that made it into the flattener, but now we no longer track change logs. I am thinking, though, it would be nice to match up to CxG schema. Sometimes, I have a flattened file in my local directory, and I am wondering what version it is. What do you think if we update FLAT_VERSION to 5.1?

Other than these two things, it looks great! The commenting is very nice and clearly laid out, and it's nice being able to go to separate files when looking at code rather than one extremely long script. Thank you!

**Comment by Jchaffer787** [comment]
I've pushed a commit to fix the uns['default_embedding'] issue, as well as change FLAT_VERSION to SCHEMA_VERSION

**Comment by jychien** [comment]
Looks great! Really nice work getting everything so organized and clearly documented.

**Pull request merged**
