### PR TITLE
Tools 145 multiplexed logging no prefix suffix

### PR DESCRIPTION
**Pull request by jychien**
@Jchaffer787 Here is the PR. Thanks! I know it's very difficult to test. Jennifer has since correct the linking for AIDA and Erica has corrected the Mukamel dataset. @jahilton Any suggestions?

### CODE REVIEW

**Comment by jahilton** [comment]
Are the incorrect linkings still present in the demo?

**Comment by jychien** [comment]
ProcMatrixFiles that I plan to run and test:

- LATDF583TQZ (Mukamel, Demo)
- LATDF453YYA (AIDA, Demo)
- LATDF190KNY
- LATDF584NGT
- LATDF329OGL
- LATDF477OUM
- LATDF994BQY

**Comment by jychien** [comment]
Looks like LATDF453YYA had additional errors, and th
Screenshot 2023-12-05 at 5 12 34 PM
erefore the flattener did not trigger the new logging. This is the error it came across:

However, it does look like I've pasted the logging during the flattening previously: https://lattice.atlassian.net/browse/TOOLS-145?focusedCommentId=17176

@jahilton Let me know if this is sufficient. Or else we'll need to partially correct AIDA in Demo.

**Comment by jahilton** [comment]
LGTM

**Pull request merged**
